[jwt]
secret_key = "jwt secret key"

[google]
info_url = "https://www.googleapis.com/userinfo/v2/me"

[facebook]
info_url = "https://graph.facebook.com/me"

[saga_addr]
url = "http://saga:8004"

[server]
address = "0.0.0.0:8000"
database = "postgresql://users:users@users-pg-postgresql/users"
thread_count = 20
